nuxtrdev/nuxtr-vscode

- README.md
- package.json
- src/commands/Structure.ts
- src/commands/index.ts
- src/extension.ts
A command to install `.nuxtrc` file.
> feat: create .nuxtrc command

- src/intellisense/completionProviders/nuxtIgnore.ts
- syntaxes/nuxtignore.tmLanguage.json
Thanks to @maninak's feedback. This PR handles the ! case for [`.nuxtignore`](https://nuxt.com/docs/guide/directory-structure/nuxtignore#nuxt-ignore-file).
> feat: handle nuxtignore ! case

- README.md
- package.json
- snippets/Nitro/imports.json
- src/commands/Middleware.ts
- src/commands/Nitro.ts
- src/commands/Plugin.ts
- src/commands/index.ts
- src/extension.ts
- src/snippets/index.ts
- src/templates/typeScriptFiles.ts
- src/types.d.ts
- src/utils/commands.ts
- src/watchers/config.ts
- ui/src/main.ts
> feat: Nitro support

- package.json
- src/commands/Nitro.ts
- src/commands/Util.ts
- src/commands/index.ts
- src/extension.ts
- src/templates/typeScriptFiles.ts
- src/utils/commands.ts
Commands and Context Menu items for [Nuxt](https://nuxt.com/docs/guide/directory-structure/utils) and [Nitro](https://nuxt.com/docs/guide/directory-structure/server#server-utilities) utilities.
> feat: commands & context menu nuxt and nitro utils

- src/content/pm.ts
- src/sideBar/index.ts
- src/types.d.ts
- src/utils/dependency.ts
> feat: Bun support

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- package.json
- src/commands/Templates.ts
- src/commands/index.ts
- src/extension.ts
- src/intellisense/completionProviders/nuxtIgnore.ts
- src/types.d.ts
- src/utils/watchers.ts
- src/watchers/config.ts
- src/watchers/index.ts
#33 
- Offering setting to choose default template language (html/pug).
- Config watcher for `vueFiles.template.defaultLanguage`.
- Configuring Pug. 
- Configuration command.
> feat: pug templates support

- src/templates/vueFiles.ts
- src/utils/vueFiles.ts
> feat: pug templates

- ui/src/composables/content.json
> chore: updating nuxt integrations

- package.json
- pnpm-lock.yaml
- src/commands/Nuxi/commonCommands.ts
- src/commands/Nuxi/index.ts
- src/commands/Nuxi/multiStepCommands.ts
- src/commands/index.ts
- src/extension.ts
> feat: nuxi module command

- package.json
- pnpm-lock.yaml
- src/commands/Devtools.ts
> fix: nuxt devtools toggle message

- src/templates/vueFiles.ts
> fix: vue templates spacing 

- README.md
- package.json
- src/commands/Component.ts
- src/commands/Layout.ts
- src/commands/Page.ts
- src/commands/Store.ts
- src/commands/Structure.ts
- src/templates/appConfig.ts
- src/templates/index.ts
- src/templates/stores.ts
- src/types.d.ts
- src/utils/files.ts
- src/utils/index.ts
- src/watchers/config.ts
- src/watchers/index.ts
#59 
Supporting Pinia Setup Templates
> feat: pinia setup template

- src/commands/Devtools.ts
> fix: handle Nuxt devtools shipped native

- snippets/Nuxt/boilerplates.json
> feat: typescript setup script snippet

- src/commands/Devtools.ts
- src/commands/Nuxi/multiStepCommands.ts
- src/index.ts
Nuxt introduced a new website and part of the changes was changing the path for Nuxt modules API. This PR is to adjust to this change.
> refactor: Nuxi Module command

- src/templates/stores.ts
- src/templates/typeScriptFiles.ts
- src/utils/file.ts
- src/utils/index.ts
> fix: hyphen naming for composables and stores

- src/utils/file.ts
> fix: vue templates location with srcDir

- package.json
- pnpm-lock.yaml
- src/commands/Devtools.ts
- ui/package.json
Closes #106
Devtools compatability checker was manually checking if Nuxt version is bigger than 3.8 or not. This PR uses semver to do the comparability checking.
> fix: devtools compatability checker

- src/utils/file.ts
- src/utils/files.ts
- tsup.config.ts
> chore: removing file creation extra lines 

- src/commands/CSS.ts
- src/extension.ts
- src/templates/css.ts
- src/templates/index.ts
- src/watchers/index.ts
- src/watchers/vscode.ts
> feaT: TailwindCSS Typescript config

- package.json
- src/utils/nuxt.ts
> fix: installed modules added to layers

- package.json
- src/commands/Devtools.ts
- src/index.ts
- src/statusBar/index.ts
closes #119
Hiding Devtools detection error messages and commands to toggle for Nuxt 2 projects.
> feat: hiding Nuxt Devtools for Nuxt 2

- package.json
- src/utils/dependency.ts
- taze.config.ts
- ui/package.json
closes #128
Bun update dependencies command detection.
> fix: Bun update dependencies command detection

- package.json
- pnpm-lock.yaml
- src/commands/Project.ts
- src/snippets/index.ts
- src/utils/dependency.ts
- src/utils/file.ts
- src/utils/files.ts
- src/watchers/config.ts
- src/watchers/index.ts
This refactor user settings. change wrong naming for an option, refactors how snippets are enabled/disabled and reduces the need to refresh VSCode / Nuxtr except for the snippets / intellisense.
> refactor: user settings
